# Generated by Django 2.2 on 2021-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210826_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
