# Generated by Django 2.2 on 2021-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20210826_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
