# Generated by Django 2.2 on 2021-08-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20210826_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='restapi.Register'),
        ),
    ]
